# Generated by Django 5.2.7 on 2025-11-01 17:25

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deprivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نام خانوادگی')),
                ('nCode', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('fName', models.CharField(max_length=100, verbose_name='نام پدر')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('cGroup', models.CharField(max_length=100, verbose_name='کد گروه')),
                ('fund_name', models.CharField(max_length=100, null=True, verbose_name='نام صندوق')),
            ],
        ),
        migrations.CreateModel(
            name='InformationFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نام خانوادگی')),
                ('nCode', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('fName', models.CharField(max_length=100, verbose_name='نام پدر')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('cGroup', models.CharField(max_length=100, null=True, verbose_name='کد گروه')),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=100, verbose_name='تعداد اعضا')),
                ('NumberOfLoans', models.CharField(max_length=100, verbose_name='تعداد وام')),
                ('mony', models.CharField(max_length=30, verbose_name='مبلغ پرداختی')),
                ('quantity', models.CharField(max_length=30, verbose_name='موجودی')),
                ('AfterTheSize', models.CharField(max_length=30, verbose_name='پس انداز')),
                ('course', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('bazaar', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('name_course', models.CharField(max_length=100, null=True, verbose_name='نام دوره')),
                ('member_course', models.CharField(max_length=100, null=True, verbose_name='تعداد شرکت کننده')),
                ('name_teacher', models.CharField(max_length=100, null=True, verbose_name='نام استاد')),
                ('phone_teacher', models.CharField(max_length=11, null=True, verbose_name='شماره استاد')),
                ('bazzar_desc', models.TextField(null=True, verbose_name='توضیحات بازارچه')),
                ('fund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resistance.informationfund')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ انجام برنامه')),
                ('address', models.CharField(max_length=150, verbose_name='آدرس')),
                ('subject', models.CharField(max_length=150, verbose_name='موضوع')),
                ('desc', models.TextField(verbose_name='توضیحات')),
                ('member', models.CharField(max_length=100, verbose_name='تعداد اعضا')),
                ('deprivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resistance.deprivation')),
            ],
        ),
    ]
